<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJEUKqfG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJEUKqfG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJEUKqfG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJEUKqfG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJEUKqfG\App_KernelDevDebugContainer([
    'container.build_hash' => 'JEUKqfG',
    'container.build_id' => '4fee7b1f',
    'container.build_time' => 1766496206,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJEUKqfG');
