<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIG96eLS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIG96eLS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIG96eLS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIG96eLS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIG96eLS\App_KernelDevDebugContainer([
    'container.build_hash' => 'IG96eLS',
    'container.build_id' => 'dff0a87a',
    'container.build_time' => 1766586598,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIG96eLS');
