<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRvg5xK6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRvg5xK6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRvg5xK6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRvg5xK6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRvg5xK6\App_KernelDevDebugContainer([
    'container.build_hash' => 'Rvg5xK6',
    'container.build_id' => '617db70c',
    'container.build_time' => 1766408492,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRvg5xK6');
